dataset:
  pdb_paths:
    - ./demo/data/mol_grow/cplx.cif
  tgt_chains:
    - AB
  lig_chains:
    - L

templates:
  # molecule growing
  - class: MoleculeCompletion
    fragment_sdf: ./demo/data/mol_grow/anchor_1.sdf
    add_block_size_min: 6
    add_block_size_max: 10  # [6, 10)


batch_size: 16
n_samples: 50  # top-50 candidates for each complex
