dataset:
  pdb_paths:
    - ./demo/data/mol_grow/cplx.cif
  tgt_chains:
    - AB
  lig_chains:
    - L

templates:
  # molecule linker
  - class: MoleculeCompletion
    fragment_sdf: ./demo/data/mol_grow/cleaned_fragments.sdf
    block_centers:
      - [16.0, 25.0, 15.0]
      - [16.0, 25.0, 16.0]
      - [15.0, 25.0, 18.0]
      - [15.0, 23.5, 19.0]
    block_center_stds: [1.0, 1.0, 1.0, 1.0]
    add_block_size_min: 4
    add_block_size_max: 5  # [4, 5), no additional random blocks


batch_size: 16
n_samples: 50  # top-50 candidates for each complex
